package dev.cannoli.scorza.libretro.settings

data class LauncherSettingsStrings(
    val rootTitle: String = "Settings",
    val categoryVideo: String = "Video",
    val categoryEmulator: String = "Emulator",
    val categoryInput: String = "Input",
    val categoryAdvanced: String = "Advanced",
    val categoryInfo: String = "Info",
    val screenScaling: String = "Screen Scaling",
    val screenSharpness: String = "Screen Sharpness",
    val shader: String = "Shader",
    val shaderSettings: String = "Shader Settings",
    val overlay: String = "Overlay",
    val maxFfSpeed: String = "Max FF Speed",
    val showFps: String = "Show FPS",
    val debugHud: String = "Debug HUD",
    val controllerType: String = "Controller Type",
    val noOptions: String = "No options available",
    val other: String = "Other",
    val on: String = "On",
    val off: String = "Off",
    val buttonMappings: String = "Button Mappings",
    val shortcuts: String = "Shortcuts",
    val leftStickDpad: String = "Left Stick as D-Pad",
    val dpadMode: String = "D-Pad Mode",
    val dpad8Way: String = "8-Way",
    val dpad4Way: String = "4-Way",
    val discard: String = "Discard",
)
